{% set name = "mdtraj" %}
{% set version = "1.8.0" %}
{% set sha256 = "480fa4c280146e91db0ab7811f6fba5da29e89452b071d366a8e68247a88ffea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Necessary for building 1.8.0, should be fixed by next version
    - 1208-find-zlib.patch

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point
  # The TNG library has a c file that declares some variables
  # not at the top of the function :o
  # This breaks older versions of visual studio. It could
  # probably be fixed by an interested party.
  #skip: True  # [win and (py27 or py34)]

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - zlib 1.2.*

  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - pytables

test:
  imports:
    - mdtraj
  commands:
    - mdconvert -h
    - mdinspect -h

about:
  home: https://github.com/mdtraj/mdtraj
  license: LGPL-2.1
  summary: "A modern, open library for the analysis of molecular dynamics trajectories"
  description: |
    MDTraj is a python library that allows users to manipulate molecular dynamics
    (MD) trajectories and perform a variety of analyses, including fast RMSD,
    solvent accessible surface area, hydrogen bonding, etc. A highlight of MDTraj
    is the wide variety of molecular dynamics trajectory file formats which are
    supported, including RCSB pdb, GROMACS xtc, tng, and trr, CHARMM / NAMD dcd, AMBER
    binpos, AMBER NetCDF, AMBER mdcrd, TINKER arc and MDTraj HDF5.
  doc_url: http://mdtraj.org/
  dev_url: https://github.com/mdtraj/mdtraj

extra:
  recipe-maintainers:
    - rmcgibbo
    - mpharrigan
