travis:
  secure:
    BINSTAR_TOKEN: Bv/B1OSfFnme4RkioEyi6GQT4419AOVxSUNJuXIfAwLT4/RwBQ9kup4/flOCfWrtp86Oq0U88H13TW3hAC3KJZlIFpPC3QIe1wUZF+sVkwTNneMcW2tV8znmXq00ziLPJ1zRvLlPTfPnD1TJJOP8g2JFQsWIGhCGOkVmx6B6suycAR+7ZwqoRIFRyZDDhbtZ/hAa5iOr2ZGf4uo89jbsOrl9PgK6PwBBUKQv2GUAGnn6ZQn+hxNUxEUoOHmgeKEeVMkt+kMz8nS1mpVVEP0lIkMQTBfVlTq22DmlHy/TzWcjyevZULFnUqFIwZmQBdfwl+2LxtA5asNQ2YTT5AG3kqryS9CbSlvWk4phce7EDBMGciTxNqCxhtjD9hDTNyp7EqR3Q2yWN37a5wxfN98VIJk3LgFaXLcIQdLTHaG/DqYh8JgWlgngIiFX+fIDIKJZLfTu1czKgMHc0D0DLxsHLBJUkpQZEbFELiDVMm2dpKsOx5DSXsAohtda6teUi2gJdJRIKNov5La1ILQGl2eikc98Tz1zCgV5lZ4Viu+p2tWBvjGeCM48NCp4IkK4q7x3dXiZY/kCZHTYjrnWxfMm7PAL/c5UYWRlgDEM7d4MWE3yM6dBofq2xWG4B/BsntU9eU+IB0PKA0xlC16eSnf6KGBsqmwQPfgbu6Dfxcs4URk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
